# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
