# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_checkout_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=models.CharField(choices=[(b'IN', b'India'), (b'US', b'United States'), (b'CH', b'China'), (b'UK', b'United kingdom')], max_length=2, null=True),
        ),
    ]
