# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-29 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
